import type { Metadata } from "next"
import "./globals.css";
import { Poppins } from 'next/font/google'
import { ToastProvider } from "@/components/ToastProvider";
import GlobalProvider from "@/components/Application/GlobalProvider";

const PoppinsFont = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PoppinsFont.className}antialiased`}
      >
        <GlobalProvider>
          {children}
          <ToastProvider />
        </GlobalProvider>
      </body>
    </html>
  );
}


